/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    ColorInput: typeof import('./src/components/ColorInput.vue')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    ColorResultCard: typeof import('./src/components/ColorResultCard.vue')['default']
    ContentCard: typeof import('./src/components/ContentCard.vue')['default']
    CopyButton: typeof import('./src/components/CopyButton.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Github: typeof import('./src/components/Github.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Magicolor: typeof import('./src/components/Magicolor.vue')['default']
    Message: typeof import('primevue/message')['default']
    Picker: typeof import('./src/components/Picker.vue')['default']
    RatioTable: typeof import('./src/components/RatioTable.vue')['default']
    RatioTableSquare: typeof import('./src/components/RatioTableSquare.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Select: typeof import('primevue/select')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
