packages:
  - packages/*

catalogs:
  devConf:
    '@antfu/eslint-config': ^5.2.1
    eslint: ^9.33.0
    typescript: ~5.9.2

  taze:
    taze: ^19.3.0

  types:
    '@types/node': ^24.3.0
    typescript: ^5.8.3
